# Generated by Django 5.0.6 on 2024-05-31 01:03

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('service_time', models.IntegerField(default=0)),
                ('remuneration', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
